### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by WenXin20** [D0CTOR-ZED/FloorMats#1] opened 2020-10-15 21:32 UTC
`Minecraft v1.15.2`
`Forge v31.2.45`
`Floor Mats v1.0.0`

I received an Internal Server Error after mining a Gold Floor Mat while standing on it.
[Server Error](https://gist.github.com/WenXin20/948c55057517bea89bbd3b20e25dbc59)

**Comment by D0CTOR-ZED** [comment] 2020-10-15 23:56
I should be able to get an update out for this when I get home tomorrow.  I have a few questions.  Were you in a single player environment?  If multiplayer, was there another player interacting with the floor mat at the time?  Were you in the process of stepping on or off as you mined the floor mat?  Either way, I can add a check to make sure this doesn't happen, I'm just looking for this info to better understand how it happened as that may help uncover other potential issues.  Thanks for reporting this issue.

**Comment by WenXin20** [comment] 2020-10-16 00:03
- It was in multiplayer, and I was the only one on the server. 
- I was stepping on the gold floor mat as I was mined and broke it.
- I was kicked from the server the moment it broke.
Thanks!

**Comment by D0CTOR-ZED** [comment] 2020-10-16 14:17
This issue should now be resolved in v1.0.1 (uploaded and pending CurseForge approval).
Please run the command "/floormats reset" after updating (removed privilege requirement in v1.0.1) to fix any data issues that may still exist in the floor mats data.  Thank you.

**Comment by WenXin20** [comment] 2020-10-19 06:59
Hello, I got the Internal Server Error again. I was standing still on the gold floor mat when I broke it. I forgot about running the command mentioned above, although the gold floor mat was placed in a completely different location this time. Maybe the [Performant](https://www.curseforge.com/minecraft/mc-mods/performant) mod is involved?
[Error Log](https://gist.github.com/WenXin20/4dc1b1ff17230e33269e37ea920a63a2)

**Comment by D0CTOR-ZED** [comment] 2020-10-19 18:57
If it was a new location, the command is irrelevant.  I'll try to do some testing with Performant.  It could definitely be a mod interaction.  Is it crashing the server, or just your client?  If you can reliably reproduce this, I can put together a release that logs a lot of data.  If you were willing, you could perhaps try with that release and forward me any crash.log and latest.log in the event you can crash that version.  Looking at what you linked, this is exactly the same issue.  The odd thing is that it shows the mat is powering up which should have already happened if you were standing on the mat.  Thank you for your patience.  Also, would it be possible to remove Performant and see if you can still reproduce the bug?
Edit: One more thing, would it be possible to get a list of mods you are using?

**Comment by WenXin20** [comment] 2020-10-19 19:06
The client is fine and the server doesn't completely crash. It just gives me an internal server error. I can try the new release and without performant. It's a big list of mods though, I wouldn't be able to list them all.

**Comment by D0CTOR-ZED** [comment] 2020-10-19 22:23
Thank you for everything.  I've determined that the issue is an interaction between my mod and performant.  With only the two mods installed, I crash when breaking a block that I'm standing on.  Without performant, I have no issue.  As performant is closed source and a core mod, I have no way of knowing what would be necessary to make the mods compatible.  I'm going to re-close the ticket.  I'll also reach out to performant to see if there is any reasonable to resolve this.

On a positive note, while reviewing my code for possible causes, I did identify something that I can do to help with performance.... same results, less processing time, so that's good.

**Closed as completed by D0CTOR-ZED** 2020-10-19 22:23 UTC
Labels: compatibility

**Comment by WenXin20** [comment] 2020-10-19 22:43
Alright, thanks for looking into it! :)

**Comment by D0CTOR-ZED** [comment] 2020-10-19 23:26
One (hopefully) final note.  In the performant config, setting **fastCollisions** to false appears to eliminate the issue.

**Comment by WenXin20** [comment] 2020-10-19 23:42
Thanks, I'll give that a try
